# Munki tasks - nginx.yml
---
- name: enable http authorization in nginx sites-available
  set_fact:
    munki_http_auth_basic: auth_basic "Restricted – Munki Repo";
    munki_http_auth_basic_user_file: auth_basic_user_file /etc/nginx/.munki_htpasswd;
  when: munki_http_password is defined

- name: create munki http authorization file
  htpasswd:
    path: /etc/nginx/.munki_htpasswd
    name: munki
    password: "{{ munki_http_password }}"
    owner: root
    group: www-data
    mode: 0640
  when: munki_http_password is defined

- name: create munki ssl config file
  template:
    src: ssl.conf.j2
    dest: /etc/nginx/snippets/ssl-munki.conf
    owner: root
    group: root
    mode: 0644
  when:
    - munki_ssl_cert_path is defined
    - munki_ssl_privkey_path is defined

- name: apply nginx sites-available template (https)
  template:
    src: https.sites-available.munki.j2
    dest: /etc/nginx/sites-available/munki
    owner: root
    group: root
    mode: 0644
  when:
    - munki_ssl_cert_path is defined
    - munki_ssl_privkey_path is defined
  register: munki_sites_available_https
  notify:
    - restart nginx

- name: apply nginx sites-available template (http)
  template:
    src: http.sites-available.munki.j2
    dest: /etc/nginx/sites-available/munki
    owner: root
    group: root
    mode: 0644
  when: munki_sites_available_https is skipped
  register: munki_sites_available_http
  notify:
    - restart nginx

- name: add munki to nginx sites-enabled
  file:
    src: /etc/nginx/sites-available/munki
    dest: /etc/nginx/sites-enabled/munki
    state: link
  notify:
    - restart nginx
